name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Set up Crane
        uses: imjasonh/setup-crane@v0.3
      - name: Build with Maven
        run: mvn --batch-mode -DskipTests compile jib:buildTar
      - name: Upload Docker image to registry
        run: crane push byblos-standalone/target/jib-image.tar ghcr.io/${{ github.repository }}/byblos